{
  <|
    "href"->"https://mathematica.stackexchange.com",
    "body"->"Mathematica Stack Exchange"
    |>,
  Replace[$$templateLib["getTemplateArguments"][#]["MainSiteURL"],{
    s_String:>
      <|
        "href"->s,
        "body"->"Main"
        |>,
    _->Nothing
    }],
  Replace[$$templateLib["getTemplateArguments"][#]["DocumentationURL"],{
    s_String:>
      <|
        "href"->s,
        "body"->"Documentation"
        |>,
    _->Nothing
    }],
  Replace[$$templateLib["getTemplateArguments"][#]["GitHubUserName"],{
    s:_String|{__String}:>
      <|
        "href"->
          URLBuild@<|
            "Scheme"->"https",
            "Domain"->"github.com",
            "Path"->Flatten@{s}
            |>,
        "body"->"GitHub"
        |>,
    _->Nothing
    }]
  }&
